language: go

sudo: false

matrix:
  include:
    - go: "1.11.x"
      env:
        - GO111MODULE=on
    - go: "1.12.x"

script:
  - GOFLAGS=-mod=vendor go test -v integration_test.go -args -- -nointeractive
